### ISSUE TITLE
README.md needs more info about your project

### ISSUE THREAD

**Issue by AleejandroReyna** [guadalupe182/contactManager#1]
The readme file justifies the existence of your project and explain how it works. 

You need to explain:

- [x] What the project does 
- [x] Stack tech
- [x]  How to setup the project for development (Example: https://github.com/AleejandroReyna/django-todolist) 

You need to remove dist folder from repo, because this files are only necessary on production env.
You don't need to describe how to install every package with npm or yarn.

**Comment by guadalupe182** [comment]
The above suggestions have been added and the .gitignore pull request has been accepted, however the dist folder still appears.
Any other way to remove it? thanks in advance.

**Comment by AleejandroReyna** [comment]
git rm -r dist

**Comment by guadalupe182** [comment]
I forgot to take it out of the stage.
Thank you very much !
